export enum ScheduleType {
	DAILY = "DAILY",
	BI_WEEKLY = "BI_WEEKLY",
	WEEKLY = "WEEKLY",
	BI_MONTHLY = "BI_MONTHLY",
	MONTHLY = "MONTHLY",
	QUARTERLY = "QUARTERLY",
	BI_ANNUALLY = "BI_ANNUALLY",
	ANNUALLY = "ANNUALLY",
}
export enum CompoundScheduleType {
	WEEKLY = "WEEKLY",
	MONTHLY = "MONTHLY",
	QUARTERLY = "QUARTERLY",
	ANNUALLY = "ANNUALLY",
}
